builder:
  image: sagacify/docker-sbt:latest
  command: sbt test
  environment:
    APP_PORT: 8081
    TEST: "true"
    TEST_DEFAULT: "true"
  ports:
    - "18081:8081"
  volumes:
    - ~/.ivy2:/root/.ivy2
    - ./src:/app/src
    - ./project:/app/project
    - ./build.sbt:/app/build.sbt
    - ./target:/app/target
